/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto_Archisoft;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author prueba
 */
public class Empleados1 extends javax.swing.JInternalFrame {

    public static String TipoBusqueda = "";

    /**
     * Creates new form Empleados
     */
    public Empleados1() {


        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Empleados");

        jLabel1.setText("Motivo de Busqueda:");

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setBackground(getBackground());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Individual", "Supervisor", "Dependencia", "General" }));
        jComboBox1.setSelectedItem(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model;
        String Cedula = jTextField1.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conexion = null;
            String[] Titulos = {"Nombre", "Direccion", "Ciudad", "Telefono", "Celular", "Fecha_Ingreso", "Nombre_Contacto", "Telefono_Contacto", "Cargo", "Jefe", "Dependencia"};
            model = new DefaultTableModel(null, Titulos);

            try {
                conexion = DriverManager.getConnection("jdbc:mysql://Localhost:3306/tecnoproyectos", "root", "andres0122");
            } catch (SQLException ex) {
                Logger.getLogger(Empleados1.class.getName()).log(Level.SEVERE, null, ex);
            }
            Statement s2 = null;
            s2 = conexion.createStatement();
            ResultSet rs = null;

            rs = s2.executeQuery("select * from empleados");

            String[] fila = new String[11];
            while (rs.next()) {

                if (TipoBusqueda.equals("General")) {
                    
                        //JOptionPane.showMessageDialog(null, "Supervisor encontrado");
                        fila[0] = rs.getString(3);
                        fila[1] = rs.getString(4);
                        fila[2] = rs.getString(5);
                        fila[3] = rs.getString(6);
                        fila[4] = rs.getString(7);
                        fila[5] = rs.getString(8);
                        fila[6] = rs.getString(9);
                        fila[7] = rs.getString(10);
                        fila[8] = rs.getString(11);
                        fila[9] = rs.getString(12);
                        fila[10] = rs.getString(13);
                        model.addRow(fila);
                     
                }else{
                    
                    if (Cedula.equals(rs.getString(2))) {
                        fila[0] = rs.getString(3);
                        fila[1] = rs.getString(4);
                        fila[2] = rs.getString(5);
                        fila[3] = rs.getString(6);
                        fila[4] = rs.getString(7);
                        fila[5] = rs.getString(8);
                        fila[6] = rs.getString(9);
                        fila[7] = rs.getString(10);
                        fila[8] = rs.getString(11);
                        fila[9] = rs.getString(12);
                        fila[10] = rs.getString(13);
                        model.addRow(fila);
                    }
                }
            }
            jTable1.setModel(model);


        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Empleados1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Empleados1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        TipoBusqueda = jComboBox1.getSelectedItem().toString();

        switch (TipoBusqueda) {
            case "Individual":
                jLabel2.setText("Identificación");
                jTextField1.setVisible(true);
                jTextField1.setText(null);
                break;
            case "Supervisor":
                jLabel2.setText("Identificación Supervisor");
                jTextField1.setVisible(true);
                jTextField1.setText(null);
                break;
            case "General":
                jLabel2.setText(null);
                jTextField1.setVisible(false);
                break;
            case "Dependencia":
                jLabel2.setText("Código Dependencia");
                jTextField1.setVisible(true);
                jTextField1.setText(null);
                break;
            default:
                break;

        }

    }//GEN-LAST:event_jComboBox1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private String String(Object selectedItem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
